# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: rusted 
#email: nemcova.silva@gmail.com
#description: >- # this means to ignore newlines until "baseurl:"
#  A paragraph describing your webpage.
baseurl: "/" # the subpath of your site
url: "suzrz.github.io" # the base hostname & protocol for your site
#twitter_username: tareqdandachi
github_username:  suzrz

# Required plugins for the theme to work properly
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: minima

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md
  - about.md
  #- categories.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]


# posts categorization
#collections:
#  category:
#    output: true
#
#defaults:
#  -
#    scope:
#      path: ""
#      type: category
#    values:
#      layout: "category"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
